touchscreen: fts_spi: Fix the missing function prototype issue in fts…
…_get_charging_status

../drivers/input/touchscreen/fts_spi/fts.c:7359:35: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int fts_get_charging_status()
                                  ^
                                   void

Change-Id: Ibacbf9e9e3226c2bdcbf58cd3160880a93acd210