drivers: power: supply: Mark lowsoc_highvolt_smooth as static
lowsoc_highvolt_smooth is a local lookup table used for SOC smoothing
in fg-gen4 and bq27z561 fuel gauge drivers.

When compiling targets that enable both CONFIG_QPNP_FG_GEN4 and
CONFIG_FUEL_GAUGE_BQ27Z561 (such as cmi), this symbol causes a duplicate
symbol linker error:

  ld.lld: error: duplicate symbol: lowsoc_highvolt_smooth
  >>> defined in built-in.a(drivers/power/supply/qcom/qpnp-fg-gen4.o)
  >>> defined in built-in.a(drivers/power/supply/qcom/bq27z561_fg.o)

Mark lowsoc_highvolt_smooth as static in qpnp-fg-gen4 and bq27z561 to
prevent symbol collisions.

Signed-off-by: Flicker372 <flicker372@outlook.com>